SouthPark

In [1]:
import pandas as pd

In [2]:
#Create a dataframe from the CSV
df = pd.read_csv("south_park_dialogue.zip")
df.head()

  Season Episode Character                                               Line
0     10       1      Stan         You guys, you guys! Chef is going away. \n
1     10       1      Kyle                        Going away? For how long?\n
2     10       1      Stan                                         Forever.\n
3     10       1      Chef                                  I'm sorry boys.\n
4     10       1      Stan  Chef said he's been bored, so he joining a gro...

In [3]:
#remove \n from Line column
df['Line'] = df['Line'].replace({'\n':''}, regex=True)
df.head()

  Season Episode Character                                               Line
0     10       1      Stan           You guys, you guys! Chef is going away.
1     10       1      Kyle                          Going away? For how long?
2     10       1      Stan                                           Forever.
3     10       1      Chef                                    I'm sorry boys.
4     10       1      Stan  Chef said he's been bored, so he joining a gro...

In [4]:
#Remove season and episode columns since these are not needed for our task
character_line_df = df.drop(columns=['Season','Episode'])
character_line_df.head()

  Character                                               Line
0      Stan           You guys, you guys! Chef is going away.
1      Kyle                          Going away? For how long?
2      Stan                                           Forever.
3      Chef                                    I'm sorry boys.
4      Stan  Chef said he's been bored, so he joining a gro...

In [5]:
#import stopwords
from nltk.corpus import stopwords

In [6]:
stop_words = set(stopwords.words('english'))

In [8]:
#using regex tokenizer to tokenize and remove special characters
from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer(r'\w+')

In [9]:
#lower case dataframe, tokenize, and apply stopwords
lower_df= character_line_df.apply(lambda x: x.str.lower())
lower_df['Line'] = lower_df['Line'].apply(tokenizer.tokenize)
lower_df['Line'] = lower_df['Line'].apply(lambda x: [item for item in x if item not in stop_words])
lower_df.columns=['character','line']

In [10]:
lower_df.head()

  character                                               line
0      stan                    [guys, guys, chef, going, away]
1      kyle                                [going, away, long]
2      stan                                          [forever]
3      chef                                      [sorry, boys]
4      stan  [chef, said, bored, joining, group, called, su...

In [24]:
#find characters with most lines
top_characters = lower_df.groupby(['character']).size().loc[lower_df.groupby(['character']).size() > 999]
top_characters
main_characters = ['butters','cartman','kyle','mr. garrison', 'randy', 'stan']

In [27]:
#filter dataframe
filtered_df = lower_df.loc[lower_df['character'].isin(main_characters)]

In [29]:
filtered_df.head()

  character                                               line
0      stan                    [guys, guys, chef, going, away]
1      kyle                                [going, away, long]
2      stan                                          [forever]
4      stan  [chef, said, bored, joining, group, called, su...
9   cartman       [gonna, miss, gonna, miss, chef, know, tell]

In [61]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder()

In [30]:
from sklearn.model_selection import train_test_split

In [69]:
train,test = train_test_split(filtered_df, random_state=14)
train

          character                                               line
39608          stan                       [way, dude, home, ec, girls]
30681          stan  [guys, getting, john, elway, football, helmet,...
8838        cartman  [want, apologize, tell, sorry, said, okay, wro...
24390          kyle                     [yummy, yummy, thank, cartman]
8628           stan                            [indiana, jones, right]
56531       butters                                             [haaa]
702            kyle                                          [cartman]
18563          stan                            [dude, realize, saying]
39392          stan                      [yeah, gonna, thankful, told]
56287       butters                  [things, oing, new, best, friend]
62186          kyle                                             [know]
24625          kyle                             [helping, us, butters]
51183          kyle                                      [cause, hate]
69158       cartman                                           [moving]
57023          stan  [give, print, us, protect, spielberg, anyone, ...
50363         randy                                       [homosexual]
63226          kyle                                             [dude]
38496          kyle      [dude, gorak, cool, original, besides, found]
70293          stan                                      [know, stuff]
14319         randy                              [stan, poke, grandma]
15984          stan  [whatever, wanna, know, gonna, throw, crap, aw...
26980          kyle                                 [sure, come, guys]
61700  mr. garrison              [chef, white, people, stole, culture]
14037       cartman  [whoa, uh, serious, oh, god, kfc, gravy, kfc, ...
13823       butters                                       [oh, thanks]
28285          stan                                             [cool]
5357        cartman  [ahahahaha, ayah, excuse, everyone, need, mome...
53264          kyle  [ih, sure, quiet, mountains, dry, humidi, humi...
50349         randy                               [new, scout, leader]
31803       cartman                            [oh, know, clyde, frog]
...             ...                                                ...
23507         randy                          [thought, surprise, came]
37314         randy                          [uuuh, want, pants, back]
34322       cartman                                           [fonzie]
17994       butters   [oh, well, sure, uh, bringer, destruction, evil]
67700       cartman                                  [people, hippies]
32060          kyle                                           [dammit]
19182         randy                           [musical, lots, subtext]
36444          kyle     [well, uh, cartman, get, practice, real, bull]
570           randy                                     [alive, alive]
9705           stan                                           [doctor]
54882          stan       [pizza, french, fries, french, fries, pizza]
25781          stan                                             [yeah]
36162          stan  [dude, cut, firewood, day, yesterday, enough, ...
1261          randy  [boys, thing, manbearpig, vice, president, des...
68862       butters                                           [really]
13874       butters  [oh, book, tellin, kill, ohhh, kill, ronald, r...
57747          stan                                            [kenny]
18787       cartman  [guys, know, pete, melman, fourth, grade, mr, ...
16643         randy                           [awwwgh, oh, fuck, yeah]
2930        cartman                             [nooooooooooooooooooo]
70337          stan  [best, wrote, scientologist, longer, pay, mone...
55134       butters                 [uhhh, right, see, guys, tomorrow]
30357          kyle                      [nice, meet, starvin, marvin]
56424          kyle                   [ms, choksondik, stinks, inside]
28299          kyle  [wow, cartman, visitors, dropped, time, go, sc...
54455          stan  [city, wok, could, say, food, makes, lose, wei...
44554       cartman                                          [thought]
22798       butters  [hey, stan, well, people, sayin, knew, along, ...
31758          kyle                      [barbra, streisand, everrrrr]
44932          stan                                                 []

[22968 rows x 2 columns]

In [66]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, f1_score, accuracy_score

rf = RandomForestClassifier(n_estimators=100, n_jobs=-1)
#accuracy_score(rf.predict(test), test)

ValueError: setting an array element with a sequence.